image: maven:3.8.4-jdk-8

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -XX:+TieredCompilation -XX:TieredStopAtLevel=1"

stages:
  - build
  - upload
  
build:
  timeout: 5m
  stage: build
  script:
      - wget --no-check-certificate https://cdn.getbukkit.org/spigot/spigot-1.15.1.jar && mvn install:install-file -Dfile=spigot-1.15.1.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.15.1-R0.1-SNAPSHOT -Dpackaging=jar
      - wget https://cdn.getbukkit.org/spigot/spigot-1.14.4.jar && mvn install:install-file -Dfile=spigot-1.14.4.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.14.4-R0.1-SNAPSHOT -Dpackaging=jar
      - wget --no-check-certificate -O paper-1.13.2.jar https://papermc.io/api/v1/paper/1.13.2/655/download && java -Dpaperclip.patchonly=true -jar paper-1.13.2.jar && mvn install:install-file -Dfile=cache/patched_1.13.2.jar -DgroupId=com.destroystokyo.paper -DartifactId=paper -Dversion=1.13.2-R0.1-SNAPSHOT -Dpackaging=jar
      - wget --no-check-certificate https://cdn.getbukkit.org/spigot/spigot-1.13.jar && mvn install:install-file -Dfile=spigot-1.13.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.13-R0.1-SNAPSHOT -Dpackaging=jar
      - wget --no-check-certificate -O paper-1.12.2.jar https://papermc.io/api/v1/paper/1.12.2/1618/download && java -Dpaperclip.patchonly=true -jar paper-1.12.2.jar && mvn install:install-file -Dfile=cache/patched_1.12.2.jar -DgroupId=com.destroystokyo.paper -DartifactId=paper -Dversion=1.12.2-R0.1-SNAPSHOT -Dpackaging=jar
      - wget --no-check-certificate -O paper-1.11.2.jar https://papermc.io/api/v1/paper/1.11.2/1104/download && java -Dpaperclip.patchonly=true -jar paper-1.11.2.jar && mvn install:install-file -Dfile=cache/patched_1.11.2.jar -DgroupId=com.destroystokyo.paper -DartifactId=paper -Dversion=1.11.2-R0.1-SNAPSHOT -Dpackaging=jar
      - wget --no-check-certificate -O paper-1.10.2.jar https://papermc.io/api/v1/paper/1.10.2/916/download && java -Dpaperclip.patchonly=true -jar paper-1.10.2.jar && mvn install:install-file -Dfile=cache/patched_1.10.2.jar -DgroupId=com.destroystokyo.paper -DartifactId=paper -Dversion=1.10.2-R0.1-SNAPSHOT -Dpackaging=jar
      - wget --no-check-certificate -O spigot-1.9.4.jar https://cdn.getbukkit.org/spigot/spigot-1.9.4-R0.1-SNAPSHOT-latest.jar && mvn install:install-file -Dfile=spigot-1.9.4.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.9.4-R0.1-SNAPSHOT -Dpackaging=jar
      - wget --no-check-certificate -O spigot-1.9.jar https://cdn.getbukkit.org/spigot/spigot-1.9-R0.1-SNAPSHOT-latest.jar && mvn install:install-file -Dfile=spigot-1.9.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.9-R0.1-SNAPSHOT -Dpackaging=jar
      - wget --no-check-certificate -O spigot-1.8.8.jar https://cdn.getbukkit.org/spigot/spigot-1.8.8-R0.1-SNAPSHOT-latest.jar && mvn install:install-file -Dfile=spigot-1.8.8.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.8.8-R0.1-SNAPSHOT -Dpackaging=jar
      - mvn org.codehaus.mojo:versions-maven-plugin:2.5:set -DnewVersion=$TRAVIS_TAG
      - mvn install -DskipTests=true --batch-mode --update-snapshots -Prelease
      
upload:
  timeout: 5m
  stage: upload
  needs:
    - 'build'
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$CLOUD_SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $CLOUD_PORT $CLOUD_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - 'scp -P $CLOUD_PORT slimeworldmanager-classmodifier/target/slimeworldmanager-classmodifier-2.2.2.jar $CLOUD_USER@$CLOUD_HOST:~/cloud/templates/dependency/slimeworldmanager/'
    - 'scp -P $CLOUD_PORT slimeworldmanager-classmodifier/target/slimeworldmanager-plugin-2.2.2.jar $CLOUD_USER@$CLOUD_HOST:~/cloud/templates/dependency/slimeworldmanager/plugins'

